require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpoilersController do

  # This should return the minimal set of attributes required to create a valid
  # Spoiler. As you add validations to Spoiler, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "film_title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpoilersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all spoilers as @spoilers" do
      spoiler = Spoiler.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spoilers).should eq([spoiler])
    end
  end

  describe "GET show" do
    it "assigns the requested spoiler as @spoiler" do
      spoiler = Spoiler.create! valid_attributes
      get :show, {:id => spoiler.to_param}, valid_session
      assigns(:spoiler).should eq(spoiler)
    end
  end

  describe "GET new" do
    it "assigns a new spoiler as @spoiler" do
      get :new, {}, valid_session
      assigns(:spoiler).should be_a_new(Spoiler)
    end
  end

  describe "GET edit" do
    it "assigns the requested spoiler as @spoiler" do
      spoiler = Spoiler.create! valid_attributes
      get :edit, {:id => spoiler.to_param}, valid_session
      assigns(:spoiler).should eq(spoiler)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spoiler" do
        expect {
          post :create, {:spoiler => valid_attributes}, valid_session
        }.to change(Spoiler, :count).by(1)
      end

      it "assigns a newly created spoiler as @spoiler" do
        post :create, {:spoiler => valid_attributes}, valid_session
        assigns(:spoiler).should be_a(Spoiler)
        assigns(:spoiler).should be_persisted
      end

      it "redirects to the created spoiler" do
        post :create, {:spoiler => valid_attributes}, valid_session
        response.should redirect_to(Spoiler.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spoiler as @spoiler" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spoiler.any_instance.stub(:save).and_return(false)
        post :create, {:spoiler => { "film_title" => "invalid value" }}, valid_session
        assigns(:spoiler).should be_a_new(Spoiler)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spoiler.any_instance.stub(:save).and_return(false)
        post :create, {:spoiler => { "film_title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spoiler" do
        spoiler = Spoiler.create! valid_attributes
        # Assuming there are no other spoilers in the database, this
        # specifies that the Spoiler created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spoiler.any_instance.should_receive(:update_attributes).with({ "film_title" => "MyString" })
        put :update, {:id => spoiler.to_param, :spoiler => { "film_title" => "MyString" }}, valid_session
      end

      it "assigns the requested spoiler as @spoiler" do
        spoiler = Spoiler.create! valid_attributes
        put :update, {:id => spoiler.to_param, :spoiler => valid_attributes}, valid_session
        assigns(:spoiler).should eq(spoiler)
      end

      it "redirects to the spoiler" do
        spoiler = Spoiler.create! valid_attributes
        put :update, {:id => spoiler.to_param, :spoiler => valid_attributes}, valid_session
        response.should redirect_to(spoiler)
      end
    end

    describe "with invalid params" do
      it "assigns the spoiler as @spoiler" do
        spoiler = Spoiler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spoiler.any_instance.stub(:save).and_return(false)
        put :update, {:id => spoiler.to_param, :spoiler => { "film_title" => "invalid value" }}, valid_session
        assigns(:spoiler).should eq(spoiler)
      end

      it "re-renders the 'edit' template" do
        spoiler = Spoiler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spoiler.any_instance.stub(:save).and_return(false)
        put :update, {:id => spoiler.to_param, :spoiler => { "film_title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spoiler" do
      spoiler = Spoiler.create! valid_attributes
      expect {
        delete :destroy, {:id => spoiler.to_param}, valid_session
      }.to change(Spoiler, :count).by(-1)
    end

    it "redirects to the spoilers list" do
      spoiler = Spoiler.create! valid_attributes
      delete :destroy, {:id => spoiler.to_param}, valid_session
      response.should redirect_to(spoilers_url)
    end
  end

end
